services:
  - type: web
    name: job-bot-web
    env: python
    rootDir: web
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn web:app --timeout 300"
    envVars:
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASSWORD
        sync: false

  - type: worker
    name: job-bot-worker
    env: python
    rootDir: worker
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python worker.py"
    envVars:
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
