import os
import logging
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime

logger = logging.getLogger(__name__)

def send_email(jobs):
    try:
        smtp_server = os.getenv('SMTP_SERVER', 'smtp.gmail.com')
        smtp_port = int(os.getenv('SMTP_PORT', '587'))
        email_user = os.getenv('EMAIL_USER', '')
        email_password = os.getenv('EMAIL_PASSWORD', '')

        if not email_user or not email_password:
            logger.error("Email credentials not found in environment variables")
            return False

        msg = MIMEMultipart()
        msg['From'] = email_user
        msg['To'] = 'yuvalaufermusic@gmail.com'
        msg['Subject'] = f'Freelance Job Listings - {datetime.now().strftime("%Y-%m-%d")}'

        body = f"Freelance Job Listings Report\nGenerated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n"

        if not jobs:
            body += "\nNo jobs found in this scraping session.\n"
        else:
            for i, job in enumerate(jobs, 1):
                body += f"\n{i}. {job['title']}\nPlatform: {job['platform']}\nBudget: {job['budget']}\nURL: {job['url']}\nFound: {job['scraped_at']}\n"

        body += "\n---\nThis email was automatically generated by your job bot."

        msg.attach(MIMEText(body, 'plain'))
        server = smtplib.SMTP(smtp_server, smtp_port)
        server.starttls()
        server.login(email_user, email_password)
        server.sendmail(email_user, 'yuvalaufermusic@gmail.com', msg.as_string())
        server.quit()

        logger.info("Email sent successfully")
        return True

    except Exception as e:
        logger.error(f"Error sending email: {str(e)}")
        return False

